import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/NavBar';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects'
import Contact from '../components/Contact';


export default function Home() {
  return (
    <div>
      <Head>
        <title>JMG | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />


    </div>
  )
}
